DROP TABLE PET_TAG_ASS;
DROP TABLE TAG;
DROP TABLE PET_PHOTO_ASS;
DROP TABLE PHOTO;
DROP TABLE PET;
DROP TABLE CATEGORY;

CREATE TABLE CATEGORY(
  ID BIGINT PRIMARY KEY,
  CATEGORY_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PET(
  ID BIGINT PRIMARY KEY,
  CATEGORY_ID BIGINT REFERENCES CATEGORY(ID),
  PET_NAME VARCHAR(255) NOT NULL,
  STATUS VARCHAR(255) NOT NULL
);

CREATE TABLE PHOTO(
  ID BIGINT PRIMARY KEY,
  PHOTO_URL VARCHAR(255) NOT NULL
);

CREATE TABLE PET_PHOTO_ASS(
  PET_ID BIGINT REFERENCES PET(ID),
  PHOTO_ID BIGINT REFERENCES PHOTO(ID)
);

CREATE TABLE TAG(
  ID BIGINT PRIMARY KEY,
  TAG_NAME VARCHAR(255) NOT NULL,
  LTAG_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PET_TAG_ASS(
  PET_ID BIGINT REFERENCES PET(ID),
  TAG_ID BIGINT REFERENCES TAG(ID)
);
